"""empty message

Revision ID: 78842ff662db
Revises: 
Create Date: 2019-02-12 22:37:24.769301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78842ff662db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('papeis_usuario_id_fkey', 'papeis', type_='foreignkey')
    op.drop_column('papeis', 'usuario_id')
    op.add_column('usuarios', sa.Column('papel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'papeis', ['papel_id'], ['sequencial'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'papel_id')
    op.add_column('papeis', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('papeis_usuario_id_fkey', 'papeis', 'usuarios', ['usuario_id'], ['sequencial'])
    # ### end Alembic commands ###
